### ISSUE TITLE
Hisat2 error

### ISSUE THREAD

**Issue by XuTianhao** [griffithlab/rnaseq_tutorial#14]
Hi, I'm experiencing errors when running the hisat2 to generate sam files.
`hisat2 -p 8 --rg-id=UHR_Rep2 --rg SM:UHR --rg LB:UHR_Rep2_ERCC-Mix1 --rg PL:ILLUMINA --rg PU:CXX1234-TGACAC.1 -x $RNA_REF_INDEX --dta --rna-strandness RF -1 $RNA_DATA_DIR/UHR_Rep2_ERCC-Mix1_Build37-ErccTranscripts-chr22.read1.fastq.gz -2 $RNA_DATA_DIR/UHR_Rep2_ERCC-Mix1_Build37-ErccTranscripts-chr22.read2.fastq.gz -S ./UHR_Rep2.sam
Warning: the current version of HISAT2 (2.0.4) is older than the version (2.167.69) used to build the index.
         Users are strongly recommended to update HISAT2 to the latest version.
Error reading block of _offs[] array: 0, 2097152
Error: Encountered internal HISAT2 exception (#1)
Command: /home/ubuntu/workspace/rna_seq/tools/hisat2-2.0.4/hisat2-align-s --wrapper basic-0 -p 8 --rg-id=UHR_Rep2 --rg SM:UHR --rg LB:UHR_Rep2_ERCC-Mix1 --rg PL:ILLUMINA --rg PU:CXX1234-TGACAC.1 -x /home/ubuntu/workspace/rna_seq/reference_genome/chr22_with_ERCC92 --dta --rna-strandness RF -S ./UHR_Rep2.sam -1 /tmp/1602.inpipe1 -2 /tmp/1602.inpipe2 
(ERR): hisat2-align exited with value 1`

Any idea what caused it?

**Comment by malachig** [comment]
As suggested by the error, it looks like the reference genome and or transcriptome index was built with a different (newer) version of HiSat than that used for the alignment step.  

You'll need to figure out what is going on there.  Perhaps try deleting the deleting the indexes and regenerating them.  Also figure out why you may have multiple versions of HiSat installed?

**Comment by malachig** [comment]
This repo is now deprecated.  New issues should go here:
https://github.com/griffithlab/rnabio.org/issues
