### ISSUE TITLE
Normalization module

### ISSUE THREAD

**Issue by ahwagner** [griffithlab/rnaseq_tutorial#15]
I think that this tutorial could use a module on normalizing the gene/transcript expression estimates provided by stringtie, before differential expression estimation.

**Comment by malachig** [comment]
Yeah. A very simplified normalization is baked into stringtie in the "ref-only" mode.  In the "ref-guided" or "de-novo" modes you merge transcript structures across all samples and then rerun stringie using this unified transcriptome reference.  This again gives you transcript estimates that are simply normalized by gene length and sequencing depth.

However, as you suggest, for a variety of reasons, additional *across-sample normalization* is often desirable.  In the resource pages and supplementary tables for the workshop we point to a variety of papers and tools relating to the topic of normalization.

I agree that it would be a great idea to have a module dedicated to this topic!

**Comment by malachig** [comment]
This repo is now deprecated.  New issues should go here:
https://github.com/griffithlab/rnabio.org/issues
