### ISSUE TITLE
HISAT2 error message

### ISSUE THREAD

**Issue by N-Awkerman** [griffithlab/rnaseq_tutorial#16]
I'm getting a couple errors when trying to run HISAT2

my input is $hisat2 -p 8 --dta -x index {-1 input1_1,input2_1 -2 input1_2,input2_1} -S [output.sam]

but I keep getting the error message: (ERR): Different number of files specified with --reads/-1 as with -2

Any help would be much appreciated.

**Comment by malachig** [comment]
This repo is now deprecated.  New issues should go here:
https://github.com/griffithlab/rnabio.org/issues
