### ISSUE TITLE
RNA-seq Test Data

### ISSUE THREAD

**Issue by malbahrani** [griffithlab/rnaseq_tutorial#17]
First of all, I want to thank you for providing this tutorial.  

I am following the thorough instruction given in Module-1 for obtaining the RNA-seq raw data set (fastq files), and I was wondering if the HBR and HUR data (HBR_UHR_ERCC_ds_5pc.tar) is available for download.  

Could please inform me if the data is available?

Thank you again!

**Comment by malachig** [comment]
Yes, it should be.  Various test data sets used in this course are available here:
https://xfer.genome.wustl.edu/gxfer1/project/gms/testdata/bams/

The one you are looking for in particular is here:
https://xfer.genome.wustl.edu/gxfer1/project/gms/testdata/bams/brain_vs_uhr_w_ercc/downsampled_5pc_chr22/

**Comment by obigriffith** [comment]
Yeah. This is a disadvantage to including the data in the AMI and using cp commands to move from S3 bucket to working dir. In the past we got the data directly from the ftp server which meant that those commands would work for people outside the course, not using the AMI.

**Comment by malbahrani** [comment]
I am so fascinated with your work @malachig @obigriffith !
Thank you both very much for the help.
