### ISSUE TITLE
ftp site for data is not working

### ISSUE THREAD

**Issue by liz-fernandez** [griffithlab/rnaseq_tutorial#2]
The ftp site with the data for the RNA-Seq tutorial does not work:

wget ftp://genome.wustl.edu/pub/rnaseq/data/brain_vs_uhr_w_ercc/downsampled_5pc_chr22/HBR_UHR_ERCC_ds_5pc.tar

**Comment by rlesurf** [comment]
For me it works with http:

wget http://genome.wustl.edu/pub/rnaseq/data/brain_vs_uhr_w_ercc/downsampled_5pc_chr22/HBR_UHR_ERCC_ds_5pc.tar

**Comment by malachig** [comment]
Hmmm, @liz-fernandez which page had the FTP URL?

**Comment by obigriffith** [comment]
I just fixed all the ftp urls to http for these paths. If you refresh any wiki page you were using you see new commands with fixed paths. Resolving.
