### ISSUE TITLE
link broken - adapter trim

### ISSUE THREAD

**Issue by frankbioinfo** [griffithlab/rnaseq_tutorial#21]
Hello Griffith Lab team members, 

Thank you for providing such a nice explanation and tutorial on RNA-Seq analysis. 

I was going over the adapter trimming tutorial, and found that this link 

wget http://genomedata.org/rnaseq-tutorial/illumina_multiplex.fa

is broken , could you please help in fixing it. 

Thank you.

**Comment by malachig** [comment]
Sorry for the inconvenience.

We switched to using a dedicated server for this recently.  The whole thing seems to be unreachable at present.  Investigating now...

**Comment by obigriffith** [comment]
That was my bad. I had an entry in the fstab file whose format used to work but was not compatible with ubuntu LTS 16.04 for some reason. When I made an AMI of the genomedata web server (in case we ever need to re-initiate from scratch), that triggered a reboot, and the fstab error prevented successful boot, and made the instance unusable. I've re-created the instance (and AMI) with the fstab entry fixed, re-associated the elastic IP, and the genomedata server is now back up. Apologies for this inconvenience.

**Comment by frankbioinfo** [comment]
Thank you Dr @malachig  and Dr @obigriffith  for your prompt response. Appreciate it.
