### ISSUE TITLE
typo in hisat2 rna strandness option

### ISSUE THREAD

**Issue by chinanicole** [griffithlab/rnaseq_tutorial#23]
Wanted to point out a small typo that gave me an issue for a good 20 minutes - when running hisat2 options the command for indicating library strandedness is incorrect. It is written as ---rna-strand**ed**ness but correct option is --rna-strandness. 

Thanks for this tutorial - it's great!

**Comment by malachig** [comment]
Thanks for pointing this out!  Fixed via: https://github.com/griffithlab/rnaseq_tutorial_wiki/commit/7493982179dd18c3c4e0328b552c2a465599899f
