### ISSUE TITLE
./stringtie_expression_matrix.pl does not work

### ISSUE THREAD

**Issue by miguelroboso** [griffithlab/rnaseq_tutorial#24]
I am trying to follow the tutorial, but I cannot get past the "expression" section.

In particular, when I try to get the expression matrix with `./stringtie_expression_matrix.pl` , I get a compilation error:

` ./stringtie_expression_matrix.pl --expression_metric=TPM --result_dirs='HBR_Rep1,HBR_Rep2,HBR_Rep3,UHR_Rep1,UHR_Rep2,UHR_Rep3' --transcript_matrix_file=transcript_tpm_all_samples.tsv --gene_matrix_file=gene_tpm_all_samples.tsv
`

`
Type of arg 1 to keys must be hash (not private array) at ./stringtie_expression_matrix.pl line 49, near "@sample_list;"
Execution of ./stringtie_expression_matrix.pl aborted due to compilation errors.
` 

I am not really an expert in PERL, so I am having some problems troubleshooting the code, but it seems that `sample_list` is not a hash (well, it says that in the error...).

How do I solve this?

**Comment by miguelroboso** [comment]
Never mind. I found the solution. 

On our server we have a very old version of perl (5.0.1).

From the perl documentation:

>  Perl releases prior to 5.12 will produce a syntax error if you try to use an array argument. In scalar context, returns the number of keys or indices.

I will ask our admin to upgrade, or I will find out how to circumvent this.

**Comment by abdo3a** [comment]
hi there i have new issue with ./stringtie_expression_matrix.pl
i got this:  
Processing data for the following 6 samples:

Could not find transcript id in line: Cvel_scaffold10	StringTie	transcript	718	1875	1000	+	.	gene_id "Cvel_145"; transcript_id "Cvel_145.t1"; cov "4.442142"; FPKM "1.879355"; TPM "3.696904";

 with the command ~/stringtie_expression_matrix.pl --expression_metric=TPM --result_dirs='cvel_cont1,cvel_cont2,cvel_cont3,cvel_mer1,cvel_mer2,cvel_mer3' --transcript_matrix_file=transcript_tpm_all_samples.tsv --gene_matrix_file=gene_tpm_all_samples.tsv
Do you have an idea what's my problem?
Regards

**Comment by OwenDonohoe** [comment]
@abdo3a I'm having the same problem now. Did you ever find a solution?

**Comment by malachig** [comment]
Hmmm, perhaps the regular expression on line 153 of the script...
```
        }elsif ($entry[8] =~ /transcript_id\s+\"(\w+)\"\;/){
```

Your entry looks like this: `transcript_id "Cvel_145.t1"`

I believe the "." character does not get matched by \w+ in Perl.

You could try modifying that line in the Perl script to this:
```
        }elsif ($entry[8] =~ /transcript_id\s+\"(\S+)\"\;/){
```

**Comment by abdo3a** [comment]
@OwenDonohoe, i didn't find any solution and i have to change to another pipeline but i will try what @malachig proposed

**Comment by CristinaFriasLopez** [comment]
Hi,
Thank you Dr Griffith!
I have the same problem and I have solved changing the line153 of the script.

abdo3a, another issue to bear in mind, is the name of the files obtained in the previous step of stringtie. The script doesn't accept other names differents of the files *gtf and *tsv. I modified some lines related with the names of the files (transcripts.gtf gene_abundances.tsv)
_my $trans_file = $dir . "/transcripts.gtf"; by ($trans_file) = grep(/\.(gtf)$/, readdir(DIR))
my $gene_file = $dir . "/gene_abundances.tsv; by ($gene_file) = grep(/\.(tsv)$/, readdir(DIR)__

Regards,

**Comment by malachig** [comment]
This repo is now deprecated.  New issues should go here:
https://github.com/griffithlab/rnabio.org/issues

**Comment by smallyu9** [comment]
Hi,
Thank you Dr Griffith!
I have solved my problem just same as abdo3a use your measures, just change code in line 153 is ok. 
Thank you very much!
