### ISSUE TITLE
Can this tutorial be done without cloud?

### ISSUE THREAD

**Issue by ag1805x** [griffithlab/rnaseq_tutorial#25]
IS it possible to undertake this tutorial on standalone system? 
I have for now installed the mentioned tools on my system and seems to be ready!

**Comment by ag1805x** [comment]
What is the exact sample we are going to analyse?

**Comment by malachig** [comment]
Yes, the goal is for this tutorial to work on a standalone system.  If that system is Ubuntu, it should work easily.  Precise details on the samples used are explained in detail in the workshop.  

https://github.com/griffithlab/rnaseq_tutorial/wiki/RNAseq-Data
