### ISSUE TITLE
RNA_Seq analysis get counts from Balgown #264

### ISSUE THREAD

**Issue by orhanbellur** [griffithlab/rnaseq_tutorial#28]
Hello Everyone,
I am new to RNA-seq analysis. First of all I 'd like give some information about my data. My data is consist of 24 SRR file related to Sex-specific and lineage-specific alternative splicing in primates. Primates are human and chimpanzees. we used RNAseq to study transcript levels in humans and chimpanzees, using liver RNA samples from three males and three females from each species. For each sex there are two replicates. Briefly, For human, I have 12 RNA-seq file: Three males x2 replicates (For example: male1 rep1,male1 rep2 and so on.) three females x 2 replicates, for chimpanzees likewise human. For RNA-seq analsis ,I am using Nature protocol.These RNA-seq data contains single reads.
1- For first step when I align these rna-seq reads to genome. I used this comman:"hisat2 -p 2 --dta -x indexes/hg.v90 project_datasets/SRR032126.fastq -S SRR032126.sam".I am not sure whether is true or not
and as I said I have 2 replicates for each sex, Should I combine this replicate on one file? İf it is, how to perform it? Or why we use the two or more replicates.
2- I used the hisat2 >stringtie >... balgown for this analysis, but I want to do the differential analysis via DeSeq2. As you konow for this ,you need to count read. How to get this count reads from balgown. Thank you...

**Comment by ahwagner** [comment]
Hello @orhanbellur. We typically reserve use of GitHub issues to questions or errors about the material presented in the repository. Here is an example of a previous issue that is relevant here: https://github.com/griffithlab/rnaseq_tutorial/issues/17.

For these types of "How do I..." questions, I recommend making a post on Biostars (https://www.biostars.org/). Not only will you get a faster response from the much larger community (compared to the rnaseq_tutorial repository maintainers), but the questions you are asking may already be answered there. If not, your question (and the answers from the community) might be a reference for others in the future.
