### ISSUE TITLE
Samtools Install 

### ISSUE THREAD

**Issue by pdellorusso** [griffithlab/rnaseq_tutorial#29]
![screen shot 2018-01-05 at 15 51 50](https://user-images.githubusercontent.com/23369975/34627900-60d10efe-f230-11e7-944f-e2bd0e664973.png)

Hey, I'm getting tripped up in the samtools installation at the make step. It's throwing this error and I don't understand it / couldn't find anything online.

Thanks a lot for the help.

**Comment by ggoban** [comment]
you need a gcc.
run follow command.
$ apt-get install build-essential
