### ISSUE TITLE
Ballgown plotting problem

### ISSUE THREAD

**Issue by ad2n15** [griffithlab/rnaseq_tutorial#33]
I  did the tutorial, typically, as it is. I used the same tools versions, but I have 2 main problems in DE visualisation.

The distribution plot of UHR vs HBR, shows a less number of genes, and the labelled genes are not the real 25 top genes of probability values.
but, when I look to my UHR_vs_HBR_gene_results_sig.tsv, I have about 310 genes, the top 25 genes (I attached the plots PDFs)
are:
IGLC3
MPPED1
PRAME
IGLV2-23
CDC45
APOBEC3B
PLA2G3
SHANK3
RP5-1119A7.17
CACNA1I
ATF4
IGLV2-14
KDELR3
ERCC-00004
Sep-03
LA16c-3G11.7
SYNGR1
MYO18B
ERCC-00002
GNAZ
MLC1
MAPK8IP2
ERCC-00130
TEF

[Tutorial_Part3_Supplementary_R_output.pdf](https://github.com/griffithlab/rnaseq_tutorial/files/2542324/Tutorial_Part3_Supplementary_R_output.pdf)
[outfile.pdf](https://github.com/griffithlab/rnaseq_tutorial/files/2542325/outfile.pdf)

**Comment by malachig** [comment]
This repo is now deprecated.  New issues should go here:
https://github.com/griffithlab/rnabio.org/issues
