### ISSUE TITLE
how to get the genes belong to one sample and gene id conversion

### ISSUE THREAD

**Issue by fatimarasool** [griffithlab/rnaseq_tutorial#35]
I am new to RNA seq data analysis. I have followed hisat2,stringtie and ballgown pipeline. I have created the list of genes by following all steps mentioned in the paper protocol. list of genes created by step number 15. This list contains all differential expressed genes present in all samples. and this list did not contain any identifier which tells me this gene belong to this sample. My question is that  how can I identify a number of differentially expressed genes belong to one sample. here mine gene list file.
`

feature | id | fc | pval | qval
-- | -- | -- | -- | --
gene | MSTRG.28632 | 0.34122 | 1.95E-05 | 0.176761
gene | MSTRG.3615 | 5.155727 | 2.21E-05 | 0.176761
gene | MSTRG.7507 | 0.251907 | 2.22E-05 | 0.176761
gene | MSTRG.70532 | 0.318647 | 2.42E-05 | 0.176761

`
same case with the trancript file 
`

geneNames | geneIDs | geneNames.1 | geneIDs.1 | feature | id | fc | pval | qval |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
. | MSTRG.165 | . | MSTRG.37909 | transcript | 94562 | 7.209395 | 6.37E-07 | 0.029347 |  
. | MSTRG.165 | . | MSTRG.26699 | transcript | 66342 | 0.095091 | 9.80E-06 | 0.117421 |  
. | MSTRG.166 | . | MSTRG.11475 | transcript | 28435 | 3.41491 | 1.17E-05 | 0.117421 |  
. | MSTRG.170 | . | MSTRG.17454 | transcript | 42831 | 16.80033 | 1.22E-05 | 0.117421 |  
. | MSTRG.173 | . | MSTRG.1249 | transcript | 3256 | 0.076575 | 1.85E-05 | 0.117421 |  

`
next question is that how can i change the gene id in these above file into ensembl format to get   gene ontology?

**Comment by pipe2710** [comment]
Hello,

How did you sort out this? I´ve seen papers publish with these identifiers but what I understand is that they are relative to the alignment.

Many thanks,
Felipe

**Comment by fatimarasool** [comment]
you can got the sequence of these gene. next you perform further analysis

**Comment by pipe2710** [comment]
How did you get the sequences of the genes? 
Did you went back to the merged.gff and get the sequence of each MSTRG? and then BLAST?

**Comment by fatimarasool** [comment]
yes

**Comment by malachig** [comment]
This repo is now deprecated.  New issues should go here:
https://github.com/griffithlab/rnabio.org/issues
