### ISSUE TITLE
I don't know how to use this  code.

### ISSUE THREAD

**Issue by 3180100753** [griffithlab/rnaseq_tutorial#39]
![image](https://octodex.github.com/images/yaktocat.png)
you can see [this website](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-0881-8)

**Comment by obigriffith** [comment]
This seems to be maybe a test of github issue functionality? Perhaps opened here accidentally instead of in a forked repo? I'm closing as the question is too vague/general and references a publication by other authors...
