### ISSUE TITLE
Getting error while loading transcripts

### ISSUE THREAD

**Issue by Manimaran-nema** [griffithlab/rnaseq_tutorial#42]
Trinotate Trinotate.sqlite init --gene_trans_map Trinity.fasta.gene_trans_map --transcript_fasta Trinity.fasta --transdecoder_pep Trinity.fasta.transdecoder.pep 
CMD: TrinotateSeqLoader.pl --sqlite Trinotate.sqlite --gene_trans_map Trinity.fasta.gene_trans_map --transcript_fasta Trinity.fasta --transdecoder_pep Trinity.fasta.transdecoder.pep --bulk_load
-parsing gene/trans map file.... done.
-loading Transcripts.
[93900]   
done.
-loading ORFs.
[160000]   
done.
CMD: echo "pragma journal_mode=memory;
pragma synchronous=0;
pragma cache_size=4000000;
.mode tabs
.import tmp.Transcript.bulk_load Transcript" | sqlite3 Trinotate.sqlite
sqlite3: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
Error, cmd: echo "pragma journal_mode=memory;
pragma synchronous=0;
pragma cache_size=4000000;
.mode tabs
.import tmp.Transcript.bulk_load Transcript" | sqlite3 Trinotate.sqlite died with ret 32512 at /home/maran/anaconda3/lib/site_perl/5.26.2/Sqlite_connect.pm line 190.
	Sqlite_connect::bulk_load_sqlite("Trinotate.sqlite", "Transcript", "tmp.Transcript.bulk_load") called at /home/maran/anaconda3/bin/TrinotateSeqLoader.pl line 223
Error, cmd: TrinotateSeqLoader.pl --sqlite Trinotate.sqlite --gene_trans_map Trinity.fasta.gene_trans_map --transcript_fasta Trinity.fasta --transdecoder_pep Trinity.fasta.transdecoder.pep --bulk_load died with ret 32512 at /home/maran/anaconda3/bin/Trinotate line 126.

Please help me to solve this issue

**Comment by malachig** [comment]
This repo is now deprecated.  New issues should go here:
https://github.com/griffithlab/rnabio.org/issues
