### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by wangshun1121** [griffithlab/rnaseq_tutorial#43]
Should there be a docker image for this tutorial?

**Comment by malachig** [comment]
Yeah, a single docker container with all tools would get pretty large and would be more painful to maintain.  but would be nice to have.  A series of docker containers, carefully organized and documented might be better.

I'm going to leave this open.  This is a good idea.

It would also give us a chance to demonstrate as a side point some of the basics of creating docker images.

**Comment by wangshun1121** [comment]
Well, you can develop a `Dockerfile` and we can construct image using this `Dockerfile` myself!

Here is an easy way to develop this `Dockerfile`: at first, make a new folder `docker` and two new files in this folder, one is `Dockerfile` and another one is `Install_Tools.sh`; in `Install_Tools.sh`, you put all command lines in [INSTALLATION](https://github.com/griffithlab/rnaseq_tutorial/wiki/Installation) sections, and in `Dockerfile` there are only few lines as below:

```
FROM ubuntu:18.04
COPY Install_Tools.sh /opt
RUN cd /opt && sh Install_Tools.sh
```

Then using following CMLs you can try to build image:

```
cd ./docker
docker build -t "rna_tutorial" .
```

**Comment by malachig** [comment]
This repo is now deprecated.  New issues should go here:
https://github.com/griffithlab/rnabio.org/issues

I will create a corresponding issue for this issue over there.
