### ISSUE TITLE
How to perform DGE with Kallisto results files

### ISSUE THREAD

**Issue by sekhwal** [griffithlab/rnaseq_tutorial#44]
Hi, I am analyzing RNA-Seq data. I have 190 PE samples (control: male, female, mutant: male, female). I used kallisto for quantifying abundances of transcripts with the same input data. 

My question is that how to perform DGE after kallisto analysis. I have prepared a signle .tsv matrix files of all samples. Should I use Deseq2 for DGE analysis. However, the number of DE should be more in abundances of transcripts rather than a gene-based method.
I am using the following command but here my data is not in equal number. Please suggest appropriate script:

names(files) <- paste0("sample", 1:187)
txi.kallisto <- tximport(files, type = "kallisto", txOut = TRUE)
head(txi.kallisto$counts)
#library(DESeq2)
sampleTable <- data.frame(condition = factor(rep(c("affected", "unaffected"), each=93)))

rownames(sampleTable) <- colnames(txi.kallisto$counts)

dds <- DESeqDataSetFromTximport(txi.kallisto, sampleTable, ~condition)

**Comment by malachig** [comment]
This repo is now deprecated.  New issues should go here please:
https://github.com/griffithlab/rnabio.org/issues
